version: '3'


services:
  sleek-airflow:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile
    image: sleek-airflow:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
